---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vm3xrrup9tqw/public_html/fieldclock
    - /bin/cp -Rf api/. $DEPLOYPATH/api/
    - /bin/cp -Rf dist/. $DEPLOYPATH/
    - /bin/cp -f /home/vm3xrrup9tqw/secure_backups/config.php $DEPLOYPATH/api/config/config.php
    - find $DEPLOYPATH -path $DEPLOYPATH/api -prune -o -type f -print | xargs chmod 644
    - find $DEPLOYPATH -path $DEPLOYPATH/api -prune -o -type d -print | xargs chmod 755
