import { useEffect, useRef } from 'react'
import { createPortal } from 'react-dom'
import { format, parseISO, getISOWeek } from 'date-fns'
import { formatCurrency } from '../../utils/format'

// Usable vertical space on a US Letter page inside PrintOverlay's @page
// margins (0.7in top/bottom), minus a small safety buffer.
const PRINT_PAGE_HEIGHT_PX = (11 - 0.7 - 0.7 - 0.2) * 96

// Shrinks `ref`'s element just before printing so its content always fits
// on exactly one page, however many rows it has — instead of a fixed font
// size that works today but overflows once more rows are added. Uses
// `zoom` rather than `transform: scale()`: a transform only changes the
// painted size, not the layout size the print engine uses to decide where
// to break pages, so it doesn't actually prevent a second page — `zoom`
// changes the real layout size, which pagination respects. Restores full
// size after printing/cancelling so the on-screen preview stays readable.
function useShrinkToFitOnePage(ref, deps) {
  useEffect(() => {
    const el = ref.current
    if (!el) return
    const fit = () => {
      el.style.zoom = 1
      const naturalHeight = el.scrollHeight
      if (naturalHeight > PRINT_PAGE_HEIGHT_PX) {
        el.style.zoom = PRINT_PAGE_HEIGHT_PX / naturalHeight
      }
    }
    const reset = () => { el.style.zoom = 1 }
    window.addEventListener('beforeprint', fit)
    window.addEventListener('afterprint', reset)
    return () => {
      window.removeEventListener('beforeprint', fit)
      window.removeEventListener('afterprint', reset)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps)
}

const COMPANY = {
  name:    'JCCS Services LLC',
  address: '1200 Woodruff Rd, Greenville, SC 29607, Suite B-3',
  phone:   '864-907-9052',
  email:   'lauragarcia@jccs-services.com',
}
const DOC_ACCENT = '#15803d' // green, to match the app's brand aesthetic

const th = {
  padding: '6px 10px',
  textAlign: 'left',
  fontSize: '0.7rem',
  fontWeight: 700,
  textTransform: 'uppercase',
  letterSpacing: '0.06em',
  color: '#64748b',
  borderBottom: '1px solid #e2e8f0',
}
const td = {
  padding: '7px 10px',
  fontSize: '0.82rem',
  borderBottom: '1px solid #f1f5f9',
  color: '#1e293b',
}

function DocFooter() {
  return (
    <p style={{ fontSize: '0.68rem', color: '#94a3b8', marginTop: '2rem', borderTop: '1px solid #f1f5f9', paddingTop: '8px' }}>
      CONFIDENTIAL — This document contains private employment information. Generated by JCCS FieldClock · {COMPANY.name} · {format(new Date(), 'MMMM d, yyyy')}
    </p>
  )
}

// ── Weekly Payroll Report (1099 employees only) ────────────────────────────
// gasByUser/bonusByUser: { [user_id]: amount } — already-aggregated per-user
// totals for the period, matching the shape PrintChecks already computes.
//
// Loan deductions are subtracted from Net here, matching how they work
// everywhere else in FieldClock (a real repayment reduces take-home pay) —
// this intentionally differs from a reference report the amounts were
// modeled after, which added a "Net Loans" figure into the total instead.
export function Weekly1099ReportDoc({ summaryData, gasByUser = {}, bonusByUser = {}, loanDeductions = {}, period, ein }) {
  const rows = summaryData.filter((e) => e.pay_type === '1099')
  const totals = { hours: 0, gross: 0, gas: 0, bonus: 0, loan: 0, net: 0 }
  const weekNum = (() => { try { return getISOWeek(parseISO(period.start)) } catch { return null } })()
  const fmtShort = (iso) => { try { return format(parseISO(iso), 'MM/dd') } catch { return iso } }

  const cols = ['Employee', '$/Hour', 'Hours', 'Gross', 'Gas', 'Bonus', 'Loan Ded.', 'Net']

  const rootRef = useRef(null)
  useShrinkToFitOnePage(rootRef, [rows.length])

  return (
    <div ref={rootRef} style={{ fontFamily: 'Arial, "Helvetica Neue", sans-serif', fontSize: '0.8rem', color: '#1e293b', lineHeight: 1.5 }}>
      <h1 style={{ fontSize: '1.4rem', fontWeight: 800, color: '#0f172a', margin: '0 0 4px' }}>Weekly Payroll Report</h1>
      <p style={{ marginBottom: '18px', fontSize: '0.8rem', color: '#475569' }}>
        Filter: {weekNum ? `Week ${weekNum} ` : ''}({fmtShort(period.start)} - {fmtShort(period.end)}) | Year: {format(parseISO(period.start), 'yyyy')} | Group: 1099 Employees
        {ein ? ` | EIN: ${ein}` : ''}
      </p>

      <table style={{ width: '100%', borderCollapse: 'collapse' }}>
        <thead>
          <tr style={{ background: DOC_ACCENT }}>
            {cols.map((h) => (
              <th key={h} style={{ ...th, color: '#fff', background: 'transparent', borderBottom: 'none', textAlign: h === 'Employee' ? 'left' : 'right' }}>{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.length === 0 && (
            <tr><td colSpan={cols.length} style={{ ...td, textAlign: 'center', color: '#94a3b8', padding: '20px 10px' }}>No 1099 employees with pay this period.</td></tr>
          )}
          {rows.map((emp, i) => {
            const gas  = (emp.gas_total ?? 0) + (gasByUser[emp.user_id] ?? 0)
            const bon  = bonusByUser[emp.user_id] ?? 0
            const loan = loanDeductions[emp.user_id] ?? 0
            const gross = emp.base_gross ?? 0
            const net   = Math.max(gross + gas + bon - loan, 0)
            totals.hours += emp.regular_hours ?? 0
            totals.gross += gross
            totals.gas   += gas
            totals.bonus += bon
            totals.loan  += loan
            totals.net   += net
            return (
              <tr key={emp.user_id} style={{ background: i % 2 ? '#f8fafc' : '#fff' }}>
                <td style={{ ...td, whiteSpace: 'nowrap' }}><strong>{emp.name}</strong></td>
                <td style={{ ...td, textAlign: 'right' }}>{formatCurrency(emp.pay_rate ?? 0)}</td>
                <td style={{ ...td, textAlign: 'right' }}>{(emp.regular_hours ?? 0).toFixed(2)}</td>
                <td style={{ ...td, textAlign: 'right' }}>{formatCurrency(gross)}</td>
                <td style={{ ...td, textAlign: 'right', color: gas > 0 ? '#16a34a' : undefined }}>{gas > 0 ? `+${formatCurrency(gas)}` : formatCurrency(0)}</td>
                <td style={{ ...td, textAlign: 'right', color: bon > 0 ? '#16a34a' : undefined }}>{bon > 0 ? `+${formatCurrency(bon)}` : formatCurrency(0)}</td>
                <td style={{ ...td, textAlign: 'right', color: loan > 0 ? '#ef4444' : undefined }}>{loan > 0 ? `-${formatCurrency(loan)}` : formatCurrency(0)}</td>
                <td style={{ ...td, textAlign: 'right', fontWeight: 700, color: DOC_ACCENT }}>{formatCurrency(net)}</td>
              </tr>
            )
          })}
          {/* Blank rows — for writing in checks prepared later in the week */}
          {Array.from({ length: 6 }, (_, i) => (
            <tr key={`blank-${i}`}>
              {cols.map((h) => (
                <td key={h} style={{ ...td, height: '26px', borderBottom: '1px solid #e2e8f0' }}>&nbsp;</td>
              ))}
            </tr>
          ))}
        </tbody>
        {rows.length > 0 && (
          <tfoot>
            <tr style={{ background: '#f1f5f9' }}>
              <td style={{ ...td, fontWeight: 700, borderBottom: 'none' }}>WEEKLY TOTALS:</td>
              <td style={{ ...td, borderBottom: 'none' }}></td>
              <td style={{ ...td, textAlign: 'right', fontWeight: 700, borderBottom: 'none' }}>{totals.hours.toFixed(2)}</td>
              <td style={{ ...td, textAlign: 'right', fontWeight: 700, borderBottom: 'none' }}>{formatCurrency(totals.gross)}</td>
              <td style={{ ...td, textAlign: 'right', fontWeight: 700, color: '#16a34a', borderBottom: 'none' }}>{totals.gas > 0 ? `+${formatCurrency(totals.gas)}` : formatCurrency(0)}</td>
              <td style={{ ...td, textAlign: 'right', fontWeight: 700, color: '#16a34a', borderBottom: 'none' }}>{totals.bonus > 0 ? `+${formatCurrency(totals.bonus)}` : formatCurrency(0)}</td>
              <td style={{ ...td, textAlign: 'right', fontWeight: 700, color: '#ef4444', borderBottom: 'none' }}>{totals.loan > 0 ? `-${formatCurrency(totals.loan)}` : formatCurrency(0)}</td>
              <td style={{ ...td, textAlign: 'right', fontWeight: 700, color: DOC_ACCENT, borderBottom: 'none' }}>{formatCurrency(totals.net)}</td>
            </tr>
          </tfoot>
        )}
      </table>

      {/* Signature row — for physical archiving sign-off */}
      <div style={{ marginTop: '36px', maxWidth: '260px' }}>
        <div style={{ borderBottom: '1px solid #1e293b', marginBottom: '6px', height: '28px' }}></div>
        <p style={{ margin: 0, fontSize: '0.75rem', color: '#64748b' }}>Prepared by</p>
        <p style={{ margin: '2px 0 0', fontSize: '0.75rem', color: '#94a3b8' }}>Date: _______________</p>
      </div>

      <DocFooter />
    </div>
  )
}

// ── Generic print-preview overlay (shared with the Documents page) ────────
export function PrintOverlay({ children, onClose }) {
  useEffect(() => {
    const s = document.createElement('style')
    s.id = 'doc-print-css'
    s.textContent = `
      @media print {
        @page { size: letter; margin: 0.7in 0.75in; }
        body > *:not(#doc-print-root) { display: none !important; }
        .no-print { display: none !important; }
        #doc-print-root { position: static !important; overflow: visible !important; padding: 0 !important; }
      }
    `
    document.head.appendChild(s)
    return () => document.getElementById('doc-print-css')?.remove()
  }, [])

  return createPortal(
    <div id="doc-print-root" style={{ position: 'fixed', inset: 0, background: '#fff', zIndex: 9999, overflowY: 'auto', padding: '1.5rem 2rem' }}>
      <div className="no-print" style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '24px', paddingBottom: '16px', borderBottom: '1px solid #e2e8f0' }}>
        <button
          onClick={() => window.print()}
          style={{ padding: '8px 20px', background: '#6366f1', color: '#fff', borderRadius: '8px', fontSize: '0.875rem', fontWeight: 600, border: 'none', cursor: 'pointer' }}
        >
          Print / Save PDF
        </button>
        <button
          onClick={onClose}
          style={{ padding: '8px 20px', background: '#f1f5f9', color: '#374151', borderRadius: '8px', fontSize: '0.875rem', fontWeight: 600, border: 'none', cursor: 'pointer' }}
        >
          Close Preview
        </button>
        <span style={{ fontSize: '0.78rem', color: '#94a3b8', marginLeft: '8px' }}>
          Tip: In the print dialog choose "Save as PDF" to keep a digital copy.
        </span>
      </div>
      <div style={{ maxWidth: '8in', margin: '0 auto' }}>
        {children}
      </div>
    </div>,
    document.body
  )
}
