import { useEffect } from 'react'
import { createPortal } from 'react-dom'
import { format, parseISO } from 'date-fns'
import { formatCurrency } from '../../utils/format'

const COMPANY = {
  name:    'JCCS Services LLC',
  address: '1200 Woodruff Rd, Greenville, SC 29607, Suite B-3',
  phone:   '864-907-9052',
  email:   'lauragarcia@jccs-services.com',
}
const DOC_BLUE = '#1e3a8a'

const th = {
  padding: '6px 10px',
  textAlign: 'left',
  fontSize: '0.7rem',
  fontWeight: 700,
  textTransform: 'uppercase',
  letterSpacing: '0.06em',
  color: '#64748b',
  borderBottom: '1px solid #e2e8f0',
}
const td = {
  padding: '7px 10px',
  fontSize: '0.82rem',
  borderBottom: '1px solid #f1f5f9',
  color: '#1e293b',
}

function DocHeader({ title, ein }) {
  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '16px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
          <img src="/jccs-logo.jpg" alt="JCCS Services" style={{ height: '54px', width: 'auto' }} />
          <div>
            <p style={{ fontSize: '1.4rem', fontWeight: 800, color: '#0f172a', margin: 0, lineHeight: 1.15 }}>{COMPANY.name}</p>
            <p style={{ fontSize: '0.78rem', color: '#334155', margin: '3px 0 0' }}>{COMPANY.address}</p>
            <p style={{ fontSize: '0.78rem', color: '#334155', margin: '1px 0 0' }}>{COMPANY.phone} · {COMPANY.email}{ein ? ` · EIN: ${ein}` : ''}</p>
          </div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <p style={{ fontSize: '1.15rem', fontWeight: 800, color: DOC_BLUE, textTransform: 'uppercase', letterSpacing: '0.02em', margin: 0, lineHeight: 1.2, maxWidth: '220px' }}>{title}</p>
          <p style={{ fontSize: '0.75rem', color: '#94a3b8', margin: '4px 0 0' }}>Generated: {format(new Date(), 'MMMM d, yyyy')}</p>
        </div>
      </div>
      <div style={{ borderBottom: `2.5px solid ${DOC_BLUE}`, marginTop: '14px', marginBottom: '20px' }} />
    </div>
  )
}

function DocFooter() {
  return (
    <p style={{ fontSize: '0.68rem', color: '#94a3b8', marginTop: '2rem', borderTop: '1px solid #f1f5f9', paddingTop: '8px' }}>
      CONFIDENTIAL — This document contains private employment information. Generated by JCCS FieldClock · {COMPANY.name} · {format(new Date(), 'MMMM d, yyyy')}
    </p>
  )
}

// ── Weekly Payroll Report (1099 employees only) ────────────────────────────
// gasByUser/bonusByUser: { [user_id]: amount } — already-aggregated per-user
// totals for the period, matching the shape PrintChecks already computes.
export function Weekly1099ReportDoc({ summaryData, gasByUser = {}, bonusByUser = {}, loanDeductions = {}, period, ein }) {
  const rows = summaryData.filter((e) => e.pay_type === '1099')
  const totals = { hours: 0, base: 0, gas: 0, bonus: 0, loan: 0, gross: 0, net: 0 }

  return (
    <div style={{ fontFamily: 'Georgia, serif', fontSize: '0.8rem', color: '#1e293b', lineHeight: 1.5 }}>
      <DocHeader title="Weekly Payroll Report" ein={ein} />

      <p style={{ marginBottom: '4px', fontSize: '1rem', fontWeight: 700, color: DOC_BLUE }}>
        Week of {format(parseISO(period.start), 'MMMM d')} – {format(parseISO(period.end), 'MMMM d, yyyy')}
      </p>
      <p style={{ marginBottom: '16px', fontSize: '0.78rem', color: '#64748b' }}>
        1099 employee payroll summary — archived copy
      </p>

      <table style={{ width: '100%', borderCollapse: 'collapse' }}>
        <thead>
          <tr style={{ background: '#0f172a' }}>
            {['Employee','Hours','Base Pay','Gas','Bonus','Loan Ded.','Gross','Net Pay'].map((h) => (
              <th key={h} style={{ ...th, color: '#cbd5e1', background: 'transparent', borderBottom: 'none', textAlign: h === 'Employee' ? 'left' : 'right' }}>{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.length === 0 && (
            <tr><td colSpan={8} style={{ ...td, textAlign: 'center', color: '#94a3b8', padding: '20px 10px' }}>No 1099 employees with pay this period.</td></tr>
          )}
          {rows.map((emp) => {
            const gas  = (emp.gas_total ?? 0) + (gasByUser[emp.user_id] ?? 0)
            const bon  = bonusByUser[emp.user_id] ?? 0
            const loan = loanDeductions[emp.user_id] ?? 0
            const gross = emp.estimated_total ?? 0
            const net   = Math.max(gross - loan, 0)
            totals.hours += emp.regular_hours ?? 0
            totals.base  += emp.base_gross    ?? 0
            totals.gas   += gas
            totals.bonus += bon
            totals.loan  += loan
            totals.gross += gross
            totals.net   += net
            return (
              <tr key={emp.user_id}>
                <td style={td}><strong>{emp.name}</strong></td>
                <td style={{ ...td, textAlign: 'right' }}>{(emp.regular_hours ?? 0).toFixed(1)}</td>
                <td style={{ ...td, textAlign: 'right' }}>{formatCurrency(emp.base_gross ?? 0)}</td>
                <td style={{ ...td, textAlign: 'right' }}>{gas > 0 ? formatCurrency(gas) : '—'}</td>
                <td style={{ ...td, textAlign: 'right' }}>{bon > 0 ? formatCurrency(bon) : '—'}</td>
                <td style={{ ...td, textAlign: 'right', color: loan > 0 ? '#ef4444' : undefined }}>{loan > 0 ? `(${formatCurrency(loan)})` : '—'}</td>
                <td style={{ ...td, textAlign: 'right', fontWeight: 600 }}>{formatCurrency(gross)}</td>
                <td style={{ ...td, textAlign: 'right', fontWeight: 700 }}>{formatCurrency(net)}</td>
              </tr>
            )
          })}
        </tbody>
        {rows.length > 0 && (
          <tfoot>
            <tr style={{ background: '#0f172a' }}>
              <td style={{ ...td, color: '#fff', fontWeight: 700 }}>TOTAL</td>
              <td style={{ ...td, textAlign: 'right', color: '#fff', fontWeight: 700 }}>{totals.hours.toFixed(1)}</td>
              <td style={{ ...td, textAlign: 'right', color: '#fff', fontWeight: 700 }}>{formatCurrency(totals.base)}</td>
              <td style={{ ...td, textAlign: 'right', color: '#fff', fontWeight: 700 }}>{formatCurrency(totals.gas)}</td>
              <td style={{ ...td, textAlign: 'right', color: '#fff', fontWeight: 700 }}>{formatCurrency(totals.bonus)}</td>
              <td style={{ ...td, textAlign: 'right', color: '#fca5a5', fontWeight: 700 }}>{totals.loan > 0 ? `(${formatCurrency(totals.loan)})` : '—'}</td>
              <td style={{ ...td, textAlign: 'right', color: '#fff', fontWeight: 700 }}>{formatCurrency(totals.gross)}</td>
              <td style={{ ...td, textAlign: 'right', color: '#fff', fontWeight: 700 }}>{formatCurrency(totals.net)}</td>
            </tr>
          </tfoot>
        )}
      </table>

      {/* Signature row */}
      <div style={{ marginTop: '36px', display: 'flex', gap: '4rem' }}>
        {['Prepared by', 'Approved by'].map((label) => (
          <div key={label} style={{ flex: 1 }}>
            <div style={{ borderBottom: '1px solid #1e293b', marginBottom: '6px', height: '28px' }}></div>
            <p style={{ margin: 0, fontSize: '0.75rem', color: '#64748b' }}>{label}</p>
            <p style={{ margin: '2px 0 0', fontSize: '0.75rem', color: '#94a3b8' }}>Date: _______________</p>
          </div>
        ))}
      </div>

      <DocFooter />
    </div>
  )
}

// ── Generic print-preview overlay (shared with the Documents page) ────────
export function PrintOverlay({ children, onClose }) {
  useEffect(() => {
    const s = document.createElement('style')
    s.id = 'doc-print-css'
    s.textContent = `
      @media print {
        @page { size: letter; margin: 0.7in 0.75in; }
        body > *:not(#doc-print-root) { display: none !important; }
        .no-print { display: none !important; }
        #doc-print-root { position: static !important; overflow: visible !important; padding: 0 !important; }
      }
    `
    document.head.appendChild(s)
    return () => document.getElementById('doc-print-css')?.remove()
  }, [])

  return createPortal(
    <div id="doc-print-root" style={{ position: 'fixed', inset: 0, background: '#fff', zIndex: 9999, overflowY: 'auto', padding: '1.5rem 2rem' }}>
      <div className="no-print" style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '24px', paddingBottom: '16px', borderBottom: '1px solid #e2e8f0' }}>
        <button
          onClick={() => window.print()}
          style={{ padding: '8px 20px', background: '#6366f1', color: '#fff', borderRadius: '8px', fontSize: '0.875rem', fontWeight: 600, border: 'none', cursor: 'pointer' }}
        >
          Print / Save PDF
        </button>
        <button
          onClick={onClose}
          style={{ padding: '8px 20px', background: '#f1f5f9', color: '#374151', borderRadius: '8px', fontSize: '0.875rem', fontWeight: 600, border: 'none', cursor: 'pointer' }}
        >
          Close Preview
        </button>
        <span style={{ fontSize: '0.78rem', color: '#94a3b8', marginLeft: '8px' }}>
          Tip: In the print dialog choose "Save as PDF" to keep a digital copy.
        </span>
      </div>
      <div style={{ maxWidth: '8in', margin: '0 auto' }}>
        {children}
      </div>
    </div>,
    document.body
  )
}
